### ISSUE TITLE
image placeholder

### ISSUE THREAD

**Issue by alvarolorentedev** [kanekotic/flightRS#8]
![flightrs](https://cloud.githubusercontent.com/assets/3071208/17628214/a02b22a6-60b4-11e6-93f3-1eb239b92917.png)

**Comment by kanekotic** [comment]
![flightrs](https://cloud.githubusercontent.com/assets/3071208/17800759/1cdc1428-65e6-11e6-9d6c-c0a93f9a8b6a.png)
